FROM ubuntu:20.04
RUN apt update
RUN apt install -y default-jdk
RUN apt install -y docker.io
RUN apt install -y maven
RUN apt install -y openssh-client
RUN apt install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common
COPY id_rsa /root/.ssh/id_rsa
RUN chmod 600 /root/.ssh/
CMD docker start